#!/bin/sh

#Written by Bloopers

#below only works with xorg
#import -window root ~/pix/$(date '+%Y%m%d-%H%M%S').png
#notify-send "screenshot saved"


#below works with wayland
grim ~/pix/$(date '+%Y%m%d-%H%M%S.png')
notify-send "screenshot saved"

