#!/bin/sh

# created by bugswriter
# edited by bloopers
# Dependencies:
# convert wal xdotool xwallpaper 

wall_dir=~/pix/wallpaper

if [ -z "$1" ]; then
  wall="$(find "$wall_dir" -type f -name "*.jpg" -o -name "*.png" | shuf -n1)"
else
  wall="$1"
fi

convert "$wall" ~/.config/wall.jpg
xwallpaper --zoom ~/.config/wall.jpg
